repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs

  - repo: https://github.com/psf/black
    rev: 24.4.2  
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

